apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: reverseproxy
          image: nchandlersmith/reverseproxy:latest
          ports:
            - containerPort: 8080


